### ISSUE TITLE
Arduino 1.8.13 Incompatibility

### ISSUE THREAD

**Issue by kerryeven** [sparkfun/Arduino_Apollo3#261]
Platform: Windows 10 19041.450 Arduino 1.8.13 Java 1.8.0_261
Device:  Tried Artemis Redboard Nano and Edge2 and no board connected
Core location: c/Users/Me/AppData/Local/Arduino15/packages/SparkFun/hardware/apollo3/2.0.0
Arduino Preferences:  Arduino_Apollo3 ... package_sparkfun_apollo3_index.json

Description:  Have been using Apollo3 Arduino through version 1.0.30.  Updated to 2.0 after adding preference above.

At initial update, I was able to Load 2.0 and run examples from ArduinoBLE github.  Tried Hello World and it worked on Edge2 but had a hardware failure on upload to the Nano...so..BLE working..NICE.  Tried to get LED control working but could not get LED to light.    Then I lost the ability to run Arduino.  Arduino Splash screen shows through Preparing Boards but never shows the normal Starting...

I can restore Arduino startup by deleting the 2.0.0 core directory.  Re-start and Board Manager to 1.2.0 works.  Selected Nano board is retained even when updating from 1.0.30 to 1.2.0.  Updating to 2.0 causes the board to revert to Arduino Yun for some reason.  Board Manager to select any SparkFun board after update results in following Arduino errors:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.Base.rebuildProgrammerMenu(Base.java:1709)
	at processing.app.Base$11.actionPerformed(Base.java:1581)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I have tried a new Arduino install on a fairly virginal Win10 machine with and without java install....same problem.

I have tried dev install as per github and same problem.

I have tried download zip and extract to core location and rename extract to 2.0.0 .. same problem.

All occur with or without board connected usb.

Selection of the SparkFun Board after update to 2.0 causing error and prevents Arduino Start.

**Comment by oclyke** [comment]
@kerryeven thanks for this report - we've observed similar behavior when using Arduino 1.8.13. For the time being you can work around this by using Arduino 1.8.12. We are working on identifying + fixing this issue.

**Comment by dobra-dobra** [comment]
I just came here to write about the same issue. On Windows 10 machine I was able to start Arduino IDE (1.8.13) after deleting 2.0.0 package from AppData\Local\Arduino15\packages\SparkFun\hardware\apollo3 folder.

**Comment by kerryeven** [comment]
1.8.12 does fix this issue

**Comment by Wenn0101** [comment]
I'll leave this open until we fix it :D

**Comment by paulvha** [comment]
the cure is the following. In boards.txt In EACH variant defined e.g. : "sfe_artemis_dk.name=Artemis Dev Kit"  it is missing an entry called ".build.core=arduino", in this example it would be called  "sfe_artemis_dk.build.core=arduino". This will tell the IDE where the core code can be found for the board. If you had selected one of the Apollo3 boards and closed the IDE, at startup it will fail as there is an empty entry for the mandatory core location in IDE 1.8.13. The workaround is adding for your board the entry ".build.core=arduino" with the right prefix for the variant.  ( e.g. sfe_artemis_dk.build.core=arduino )  It solved the issue for me.

**Comment by ArizonaClark** [comment]
This appears to be the same problem I'm having running Arduino 1.8.13 under OS-X 10.13.6.

If you refer to the Forum thread https://forum.sparkfun.com/viewtopic.php?f=169&t=53466

Paulvha posted a new version of the file boards.txt which, regretfully, has an error in line 207, but when I commented that line out, I was able to both compile the ArduinoBLE examples I tried, AND successfully quit and restart Arduino.

**Comment by paulvha** [comment]
I have updated the boards.txt file. Attached.
[boards.txt](https://github.com/sparkfun/Arduino_Apollo3/files/5219862/boards.txt)

**Comment by TankMasterRL** [comment]
> I have updated the boards.txt file. Attached.
> [boards.txt](https://github.com/sparkfun/Arduino_Apollo3/files/5219862/boards.txt)

Will you create a PR?

**Comment by oclyke** [comment]
Thanks a ton @paulvha!

I suspected it would be something like that.... and even remember testing this in 1.8.12 (I tried to leave out any options that were unnecessary - it turns out 1.8.12 can tolerate this missing but 1.8.13 cannot)

I'll suggest a fix
