### ISSUE TITLE
Permission error MacOS with 2.2.0

### ISSUE THREAD

**Issue by sylgeist** [sparkfun/Arduino_Apollo3#435]
Same sketch before and after test:

Arduino: 1.8.16 (Mac OS X), Board: "RedBoard Artemis ATP, 460800, SparkFun Variable Loader (Recommended)"

Sketch uses 126276 bytes (12%) of program storage space. Maximum is 983040 bytes.
Global variables use 41944 bytes (10%) of dynamic memory, leaving 351272 bytes for local variables. Maximum is 393216 bytes.
java.io.IOException: Cannot run program "/Users/sylgeist/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.0/tools/uploaders/svl/dist/macosx/svl": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:11)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.SerialUploader.runCommand(SerialUploader.java:383)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:197)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2061)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 11 more
An error occurred while uploading the sketch

**Comment by sylgeist** [comment]
Looks like it just needs a `chmod +x` on the file to get it cooperating.

**Comment by Wenn0101** [comment]
Thanks for the report. I'll get this fixed ASAP.

**Comment by sylgeist** [comment]
Thanks for all the work you're doing on these! Much appreciated!

**Comment by Wenn0101** [comment]
Alright, I have it working here on my mac. Can you reinstall v2.2.0 to confirm the issue is fixed? (revert to a previous version and upgrade back to 2.2.0)

**Comment by sylgeist** [comment]
Will do - standby!

**Comment by sylgeist** [comment]
Looking good now!

```
ls -l /Users/sylgeist/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.0/tools/uploaders/svl/dist/macosx/svl
-rwxrwxr-x  1 sseekamp  staff  5905461 Dec  9 12:13 /Users/sylgeist/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.0/tools/uploaders/svl/dist/macosx/svl
```
